string input/ouput api
algorithmiaio/algorithmia-swift pull request #1
Opened 2016-11-01 18:38 UTC by erik-ilyin

2016-11-02 05:09 UTC, anowell requested changes
Overall, I'm really happy with the quality of these first commits. I just have a couple minor comments and one API design consideration. I can merge this PR if you remove the API key. The other comments can be addressed in this PR or in a separate one - whichever you prefer.

2016-11-02 05:09 UTC, anowell commented on Algorithmia/Client/AlgoRequest.swift
> +        return self;
This is a clever pattern, but it took me a while to realize `pipe` doesn't actually make the HTTP request, but rather the request is deferred until the call to `asText`. I think it's a bit surprising if `pipe` (which means "pipe data to the algorithm") is just a request builder and `asText` is the method that actually makes the API call.

What if the `pipe` method accepted your `completionHandler` instead of depending on this `asText` chain? Something like this:

``` swift
func pipe(input:String!, completionHandler:@escaping(AlgoResponse?, Error?)-> Void) -> Void
```

(that is the first line of swift I've ever tried writing, so it could be very wrong!)

2016-11-02 05:09 UTC, anowell commented on Algorithmia/Client/AlgoAPIClient.swift
> +
Also add a `User-Agent` header. Something like `"algorithmia-swift/CLIENT_VERSION (Swift SWIFT_VERSION)"` is the pattern other clients try to use. This allows us to gather metrics for each of our clients.

2016-11-02 05:09 UTC, anowell commented on AlgorithmiaSwiftDemo/AlgorithmiaSwiftDemo/ViewController.swift
> +        let client = Algorithmia.client(simpleKey: "simeH+d9MCtPoMSpXS0qjIUJuuF1")
Please remove your API key. And you should rotate your API key now, since this is a public repo (otherwise anybody can make API calls on your behalf). Normally we can test clients by setting the environment variable: `ALGORITHMIA_API_KEY`, but I'm not sure what the best way to do that while testing from a ViewController.

2016-11-02 05:09 UTC, anowell commented on Algorithmia/AlgorithmiaClient.swift
> +        self.apiClient = AlgoAPIClient(auth: nil)
Default client should use the environment variable `ALGORITHMIA_API_KEY` as the API key if it is available. If it's not, then `nil` is fine.

2016-11-02 17:12 UTC, anowell approved these changes

2016-11-02 17:13 UTC, merged

2016-11-11 19:21 UTC, jamesatha commented on Algorithmia/Client/AlgoAPIClient.swift
> +    static let apiBaseURL=URL(string: "https://api.algorithmia.com/v1/algo/")!
Above, @anowell mentioned that we allow setting the API url from an environment variable. "https://api.algorithmia.com/" shouldn't be a constant like this. We should pass in a base path here and join that with "/v1/algo"

2016-11-11 19:21 UTC, jamesatha commented on Algorithmia/AlgorithmiaClient.swift
> +        self.apiClient = AlgoAPIClient(auth: nil)
I think we need a field like `self.baseApiAddress` here. The constructor should take a baseApiAddress. If it is not null, set it to the value passed in. If not, use the environment variable. Lastly, we can default to "https://api.algorithmia.com".

This makes it easier for us to use this client to hit our non-prod environments. For an example of this, look at https://github.com/algorithmiaio/algorithmia-r/blob/master/R/Client.r#L4-L10